# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
r_github_packages:
  - rorynolan/filesstrings
after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
apt_packages:
  - libtiff4-dev
  - libgdal-dev